### UseBalance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 1000
}

### UseBalance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 1000
}


### CancelBalance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "51fdf8543c434b89857a4ad3f88d039d",
  "accountNumber": "1000000000",
  "amount": 1000
}


### GetTransactions
GET http://localhost:8080/transaction/51fdf8543c434b89857a4ad3f88d039d
Content-Type: application/json