### UseBalance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 10000
}


### CancelBalance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "657ee9aea93d41ba9fe430cabd3a3a77",
  "accountNumber": "1000000000",
  "amount": 1000
}


### GetTransactions
GET http://localhost:8080/transaction/4801535910a14b7fbdad548a409fde3a
Content-Type: application/json